### ISSUE TITLE
Cannot import `END`

### ISSUE THREAD

**Issue by ron-wolf** [czheo/syntax_sugar_python#16]
Attempting to import `END` from `pipes.py` results in an `ImportError`. The rest of the library appears to work just fine.

```python
>>> from syntax_sugar import *
>>> from functools import partial
>>> pipe(10) | range | partial(map, lambda x: x**2) | list | print | END
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'END' is not defined
>>> from syntax_sugar import END
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'END'
>>> pipe(10) | range | partial(map, lambda x: x**2) | list | print
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
<syntax_sugar.pipe.pipe object at 0x104d35128>
>>> 
```

**Comment by czheo** [comment]
would you please try `pip show syntax_sugar` to make sure the lib is the newest version 0.2.2?
